email:
  smtp_server: "smtp.yourrelay.local"
  smtp_port: 25
  # options: none, tls, ssl
  auth_type: "tls"
  # optional username if auth needed
  smtp_user: ""
  # optional password if auth needed
  smtp_pass: ""

  realtime_recipients:
    # SOC/mailbox that wants realtime alerts + errors
    - "soc@example.com"
  digest_recipients:
    # team mailboxes for daily digest
    - "alerts@example.com"
    - "it-team@example.com"

  email_from: "cve-alerts@example.com"
  subject_template: "[CVE Digest] {count} New CVEs ({date})"

logging:
  log_file: "/var/log/cve_alert.log"
  # DEBUG, INFO, WARNING, ERROR
  log_level: "INFO"
  # options: daily, size, none
  rotation: "daily"
  # if rotation enabled
  backup_count: 7
  # only used if rotation=size
  max_size_mb: 5

filters:
  products:
    - vendor: "microsoft"
      # OR ["office", "windows 11", "windows 10"] - Wildcards accepted
      product: "office"
      # match either Office 2019 or 365. Optional, wildcards accepted.
      version: ["2019", "365"]
    - vendor: "sonicwall"
      product: "*"
    - vendor: "fortinet"
      product: "fortigate"
  min_cvss: 7.0